NAME = "Catbot"
PLAYING = [
    "Catting around",
    "Not caring about you",
    "Walking on keyboards",
    "The piano",
    "Bapping household objects",
    "Ignoring you",
    "Knocking stuff over",
    "Making strange noises at birds",
    "Snoozin'",
    "STALKING =@w@="
]
RESPONSES = [
   "_The cat completely ignores you._",
   "_The cat glares at you._",
   "_The cat turns its head up at you._",
   "_The cat clicks its tongue._",
   "_The cat rifles through your wallet._",
   "_The cat looks away from you._",
   "_The cat nudges you away with its head._",
   "_The cat plops down on your keyboard. That'll show you._",
   "_The cat's ears perk up._",
   "_Upon hearing its name, the cat goes completely numb._",
   "_The cat silently rejects you._",
   "Mroo? ='w'=",
   "Myon? ='w'=",
   "MyEH ，hEH =｀ω´=",
   "_The cat looks up at you and mouths something vulgar._",
   "_The cat just wants to be loved._",
   "Myerp! =owo=",
   "Myoo!! =①ω①=",
   "Nyeh! =●⋏●=",
   "NYEHEHEH! ლ(●ↀωↀ●)ლ",
   "_The cat meows at you._",
   "_The cat begins catting immediately._",
   "_Upon being noticed, the cat challenges you to a staring match._",
   "https://www.youtube.com/watch?v=IuysY1BekOE",
   "_The cat chitters at you._",
   "_The cat myerps at you._",
   "_The cat suffers a segfault and crashes. Rebooting..._",
   "_The cat starts sharpening its claws on the carpet._",
   "_The cat wants a pet._",
   "Pets please!! =^_^=",
   "=^w^=",
   "_The cat begins to dedotate more WAM to process bein' poked._"
]
